device: "cuda"
temp_dir: "/home/hk-project-starter-p0022892/uwlat/Emotion-Recognition-API/temp_files"

qwen:
  qwen_model_path: "Qwen/Qwen2.5-VL-7B-Instruct"
  use_flash_attention: true

janus:
  use_janus: true
  janus_model_path: "deepseek-ai/Janus-Pro-7B"
