device: "cuda"
qwen_model_path: "Qwen/Qwen2.5-VL-7B-Instruct"
janus_model_path: "deepseek-ai/Janus-Pro-7B"
use_flash_attention: true
use_janus: true
temp_dir: "/home/hk-project-starter-p0022892/uwlat/Emotion-Recognition-API/temp_files"