device: "cpu"
qwen_model_path: "Qwen/Qwen2.5-VL-7B-Instruct"
janus_model_path: "deepseek-ai/Janus-Pro-7B"
use_flash_attention: false
use_janus: false
temp_dir: "/Users/lorenzneugebauer/PycharmProjects/Emotion-Recognition-API/temp_files"